### ISSUE TITLE
Missing main.py?

### ISSUE THREAD

**Issue by nickheidke** [AustinHasten/PlexHolidays#5]
I'm not seeing main.py in the code base. Is the init step supposed to put that somewhere? Apologize, I'm not a python expert by any means.

**Comment by AustinHasten** [comment]
__init__.py is the "main.py".

**Comment by nickheidke** [comment]
When I try running `python .\__init__.py` I get the following error:

>  File ".\__init__.py", line 61
>   self.pbar = tqdm(self.plex.media, desc=f'{self.plex.section.title}')
>  SyntaxError: invalid syntax

I did successfully run `python -m pip install -r requirements.txt` already.

**Comment by AustinHasten** [comment]
Looks like you might be on a version of Python < 3.6.0. I should note that in the ReadMe.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nickheidke** [comment]
That was it, thank you for the help!
